import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import { Inter } from 'next/font/google'
import App from '@/components/App'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* This component includes the Algolia InstantSearch provider.
          * All Algolia components should be set inside of it.
          * If using a site-wide searchbar, it's recommended to set it in the
          * outer section of the React App (ie. in the App section.)
          */}
        <App>
          <Navbar />
          {children}
        </App>
      </body>
    </html>
  )
}
